name: Node.js CI

on:
  push:
    branches:
      - main
      - feature/*
      - bugfix/*
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js
      uses: actions/setup-node@v3
      with:
        node-version: 20.x
        cache: 'npm'
    - name: Install dependencies
      run: npm ci
    - name: Build application
      run: npm run build
    - name: Run ESLint
      run: npm run lint
    - name: Run unit tests
      run: npm run test:prod

  upload:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/upload-artifact@v3
        with:
          name: artifacts
          path: dist/dev-tool-box/browser/

  deploy:
    needs:
    - build
    - upload
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/download-artifact@v3
        with:
          name: artifacts
          path: dist/dev-tool-box/browser/
      - uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_DEFAULT_REGION }}
      - name: Sync to S3
        run: aws s3 sync dist/dev-tool-box/browser/ s3://${{ secrets.S3_BUCKET }}

      - name: CloudFront cache invalidation
        run: aws cloudfront create-invalidation --distribution-id ${{ secrets.CLOUDFRONT_DISTRIBUTION_ID }} --paths "/*"
