name: E2E Tests

permissions:
  contents: read

on:
  workflow_run:
    workflows: [Build SPA]
    types:
      - completed

concurrency:
  group: e2e-tests-${{ github.event.workflow_run.head_branch }}
  cancel-in-progress: true

jobs:
  e2e-tests:
    if: github.event.workflow_run.conclusion == 'success'
    runs-on: ubuntu-latest
    strategy:
      matrix:
        browser: [chrome, firefox, edge]
      fail-fast: false
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 1

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20.x
          cache: npm

      - name: Install dependencies
        run: npm ci

      - name: Download build artifacts
        uses: actions/download-artifact@v4
        with:
          name: devtoolbox-artifacts
          path: dist/dev-tool-box/browser/
          github-token: ${{ secrets.GITHUB_TOKEN }}
          run-id: ${{ github.event.workflow_run.id }}

      - name: Run E2E tests with Cypress
        uses: cypress-io/github-action@v6
        with:
          start: npm run start
          wait-on: http://localhost:4200
          browser: ${{ matrix.browser }}
          record: false
          spec: cypress/e2e/**/*.cy.ts

      - name: Upload Cypress screenshots
        uses: actions/upload-artifact@v4
        if: failure()
        with:
          name: cypress-screenshots-${{ matrix.browser }}
          path: cypress/screenshots/
          retention-days: 7
          if-no-files-found: ignore

      - name: Upload Cypress videos
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: cypress-videos-${{ matrix.browser }}
          path: cypress/videos/
          retention-days: 7
          if-no-files-found: ignore
